openapi: 3.0.0
info:
  title: ScalarTax
  description : Products API Documentation
  version: 1.0.0
  contact:
    name: API Support
    url: http://example.com/supportt
    email: support@example.com
  termsOfService: http://example.com/terms/
servers:
  - url: http://localhost:3001/scalarhubio
    description: Local server
paths:  
  /scalartax/products/:
    post:
      tags:
        - Products
      summary: Create Product
      description: This endpoint allows you to add a new product to the scalartax's list of products.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
        description: Product object
        required: true               
      responses:
        '201':
          description: Product Created successfully  
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
                example:
                  message: Products created successfully
                  products:
                    - id: string
                      product_code: string
                      description: string
                      tax_code: string
                      product_group: string
                      category: string
                      entity_id: string
                      created_by_id: string
                      updated_by_id: string
                      created_at: datetime
                      updated_at: datetime
                      product_attributes:
                        - id: string
                          product_id: string
                          attribute_name: string
                          attribute_value: string
                          attribute_unit_of_measure: string
                          created_by_id: string
                          updated_by_id: string
                          created_at: datetime
                          updated_at: datetime
                        - id: string
                          product_id: string
                          attribute_name: string
                          attribute_value: string
                          attribute_unit_of_measure: string
                          created_by_id: string
                          updated_by_id: string
                          created_at: datetime
                          updated_at: datetime         
        '422':
          description:  Unprocessable Entity. Validation errors occurred during the creation.
          content:
            application/json:
              schema:
                type: object
                example:
                  errors: [ Failed to Create Products ]
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error.
    get:
      tags:
        - Products
      summary: List Products
      description: This endpoint retrieves the details of all products.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
                example:
                  - id: string
                    product_code: string
                    description: string
                    tax_code: string
                    product_group: string
                    category: string
                    entity_id: string
                    created_by_id: string
                    updated_by_id: string
                    created_at: datetime
                    updated_at: datetime
                    product_attributes: 
                      - id: string
                        product_id: string
                        attribute_name: string
                        attribute_value: string
                        attribute_unit_of_measure: string
                        created_by_id: string
                        updated_by_id: string
                        created_at: datetime
                        updated_at: datetime
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /scalartax/products/{id}:
    get:
      tags:
        - Products
      summary: Fetch Product
      description: The response will include the following details of the product.
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
                example:
                  id: PRD20241005153042260bf851f1b44e3
                  product_code: '126'
                  description: TestProduct
                  tax_code: Test Product
                  product_group: H&M
                  category: Jeans
                  entity_id: ENT20241005142022f498b677a0dc4dd
                  created_by_id: USR2024100418364856b383bf1b774eb
                  updated_by_id: USR2024100418364856b383bf1b774eb
                  created_at: '2024-10-05T10:00:42.841Z'
                  updated_at: '2024-10-05T10:00:42.841Z'
                  product_attributes: []
        '404':
          description: Not Found. Product with that Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Product Not Found.
        '500':
          description: Internal Serval Error.
    put:
      tags:
        - Products
      summary: Update Product
      description: This API endpoint is used to update the details of a specific product for a tenant.
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product1"
        required: true
      responses:
        '200':
          description: OK. Product Updated Successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product1"
                example:
                  updated_by_id: string
                  product_code: string
                  product_group: string
                  category: string
                  description: string
                  tax_code: string
                  entity_id: string
                  id: string
                  created_by_id: string
                  created_at: datetime
                  updated_at: datetime
                  product_attributes: 
                    - id: string
                      product_id: string
                      attribute_name: string
                      attribute_value: string
                      attribute_unit_of_measure: string
                      created_by_id: string
                      updated_by_id: string
                      created_at: datetime
                      updated_at: datetime
        '400':
          description: Bad Request
        '404':
          description: Not Found.Product with that Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Product Not Found.
        '422':
          description: Unprocessable Entity. Validation errors occurred during the update.
          content:
            application/json:
              schema:
                type: object
                example:
                  errors: [ Product code can't be blank,Category is invalid ]
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Products
      summary: Delete Product
      description: This endpoint is used to delete a specific product belonging to a tenant.
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Ok. Product Deleted successfully  
        '404':
          description: Not Found. Product with the Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Failed to delete the Product
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Product:
      type: object
      properties:
        products:
          type: array
          items:
            type: object
            properties:
              product_code:
                type: string
                description: The unique code for the product
              description:
                type: string
                description: A brief description of the product
              tax_code:
                type: string
                description: Tax code associated with the product
              product_group:
                type: string
                description: The product group (e.g., electronics, accessories)
              category:
                type: string
                description: The category of the product (e.g., mobile, laptop)
              entity_id:
                type: string
                description: ID of the entity associated with the product
              created_by_id:
                type: string
                description: ID of the user who created the product (nullable)
              updated_by_id:
                type: string
                description: ID of the user who last updated the product (nullable)
              product_attributes:
                type: array
                items:
                  type: object
                  properties:
                    attribute_name:
                      type: string
                      description: The name of the product attribute (e.g., Color, Battery Life)
                    attribute_value:
                      type: string
                      description: The value for the product attribute (e.g., Black, 12 hours)
                    attribute_unit_of_measure:
                      type: string
                      description: The unit of measurement for the attribute (nullable)
            required:
              - product_code
              - description
              - tax_code
              - product_group
              - category
              - entity_id
              - product_attributes
    Product1:
      type: object
      properties:
        product:
          type: object
          properties:
            products:
              type: array
              items:
                type: object
                properties:
                  product_code:
                    type: string
                    description: Unique identifier for the product
                  product_group:
                    type: string
                    description: Category of the product (e.g., Electronics, Accessories)
                  category:
                    type: string
                    description: Subcategory of the product (e.g., Laptop, Mouse)
                  description:
                    type: string
                    description: Detailed description of the product
                  tax_code:
                    type: string
                    description: Tax code associated with the product
                  entity_id:
                    type: string
                    description: Unique identifier for the entity the product belongs to
                  created_by_id:
                    type: string
                    description: ID of the user who created the product (nullable)
                  updated_by_id:
                    type: string
                    description: ID of the user who last updated the product (nullable)
                  product_attributes:
                    type: array
                    items:
                      type: object
                      properties:
                        attribute_name:
                          type: string
                          description: Name of the product attribute (e.g., Color, Battery Life)
                        attribute_value:
                          type: string
                          description: Value of the product attribute (e.g., Black, 1.5 Years)
                        attribute_unit_of_measure:
                          type: string
                          description: Unit of measurement for the attribute (nullable)
                      required:
                        - attribute_name
                        - attribute_value
                        - attribute_unit_of_measure
                required:
                  - product_code
                  - product_group
                  - category
                  - description
                  - tax_code
                  - entity_id
                  - product_attributes
