openapi: 3.0.0
info:
  title: ScalarTax
  description : Subscriptions API Documentation
  version: 1.0.0
  contact:
    name: API Support
    url: http://example.com/supportt
    email: support@example.com
  termsOfService: http://example.com/terms/
servers:
  - url: http://localhost:3001/scalarhubio
    description: Local server
paths:
  /scalartax/subscriptions:
    get:
      tags:
        - Subscriptions
      summary: List Subscriptions
      description: This endpoint retrieves a list of subscriptions related to scalar tax.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subscription"
                example: 
                  - id: string
                    plan_id: string
                    account_id: string
                    start_date: string
                    end_date: datetime
                    due_date: string
                    created_by_id: string
                    updated_by_id: string
                    status: string
                    created_at: datetime
                    updated_at: datetime
                    remaining_days: number
                    account:
                      id: string
                      name: string
                      subscription_id: string
                      created_by_id: string
                      updated_by_id: string
                      plan_name: string
                      effective_date: datetime
                      account_status: string
                    plan:
                      id: string
                      name: string
                      description: string
                      list_price: float
                      discount_price: float
                      effective_price: float
                      total_price: float
                      discount_start: null || number
                      discount_end: null || number
                      max_users: number
                      created_by_id: string
                      updated_by_id: string
                      billing_cycle: string
                      created_at: datetime
                      updated_at: datetime
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /scalartax/subscriptions/{id}:
    get:
      tags:
        - Subscriptions
      summary: Fetch Subscription
      description:  This API endpoint is used to access the details of a specific Transaction.
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subscription"
                example: 
                  - id: string
                    plan_id: string
                    account_id: string
                    start_date: string
                    end_date: datetime
                    due_date: string
                    created_by_id: string
                    updated_by_id: string
                    status: string
                    created_at: datetime
                    updated_at: datetime
                    remaining_days: number
                    account:
                      id: string
                      name: string
                      subscription_id: string
                      created_by_id: string
                      updated_by_id: string
                      plan_name: string
                      effective_date: datetime
                      account_status: string
                    plan:
                      id: string
                      name: string
                      description: string
                      list_price: float
                      discount_price: float
                      effective_price: float
                      total_price: float
                      discount_start: null || number
                      discount_end: null || number
                      max_users: number
                      created_by_id: string
                      updated_by_id: string
                      billing_cycle: string
                      created_at: datetime
                      updated_at: datetime
        '404':
          description: Not Found. Subscription with that Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Subscription Not Found.
        '500':
          description: Internal Serval Error.
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Subscription:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the subscription
        plan_id:
          type: string
          description: Unique identifier for the associated plan
        account_id:
          type: string
          description: Unique identifier for the associated account
        start_date:
          type: string
          format: date-time
          description: Start date of the subscription
        end_date:
          type: string
          format: date-time
          description: End date of the subscription
        due_date:
          type: string
          format: date-time
          description: Payment due date for the subscription
        created_by_id:
          type: string
          description: Identifier of the user who created the subscription
        updated_by_id:
          type: string
          description: Identifier of the user who last updated the subscription
        status:
          type: string
          enum:
            - ACTIVE
            - INACTIVE
            - CANCELED
          description: Current status of the subscription
        created_at:
          type: string
          format: date-time
          description: Date and time when the subscription was created
        updated_at:
          type: string
          format: date-time
          description: Date and time when the subscription was last updated
        remaining_days:
          type: integer
          description: Number of remaining days in the subscription
        account:
          $ref: "#/components/schemas/Account"
        plan:
          $ref: "#/components/schemas/Plan"
      required:
        - id
        - plan_id
        - account_id
        - start_date
        - end_date
        - due_date
        - created_by_id
        - updated_by_id
        - status
        - created_at
        - updated_at
        - account
        - plan

    Account:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the account
        name:
          type: string
          description: Name of the account
        subscription_id:
          type: string
          description: Subscription ID associated with the account
        created_by_id:
          type: string
          description: Identifier of the user who created the account
        updated_by_id:
          type: string
          description: Identifier of the user who last updated the account
        plan_name:
          type: string
          description: Name of the associated subscription plan
        effective_date:
          type: string
          format: date-time
          description: Date when the account becomes effective
        account_status:
          type: string
          enum:
            - Active
            - Inactive
            - Suspended
          description: Current status of the account
      required:
        - id
        - name
        - subscription_id
        - created_by_id
        - updated_by_id
        - plan_name
        - effective_date
        - account_status
    
    Plan:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the plan
        name:
          type: string
          description: Name of the plan
        description:
          type: string
          description: Description of the plan
        list_price:
          type: number
          format: float
          description: Original price of the plan
        discount_price:
          type: number
          format: float
          description: Discounted price of the plan
        effective_price:
          type: number
          format: float
          description: Final effective price after applying discounts
        total_price:
          type: number
          format: float
          description: Total price of the plan
        discount_start:
          type: string
          format: date-time
          nullable: true
          description: Start date for any discounts (if applicable)
        discount_end:
          type: string
          format: date-time
          nullable: true
          description: End date for any discounts (if applicable)
        max_users:
          type: integer
          description: Maximum number of users allowed under the plan
        created_by_id:
          type: string
          nullable: true
          description: Identifier of the user who created the plan
        updated_by_id:
          type: string
          nullable: true
          description: Identifier of the user who last updated the plan
        billing_cycle:
          type: string
          enum:
            - MONTHLY
            - QUARTERLY
            - ANNUAL
          description: Billing cycle of the plan
        created_at:
          type: string
          format: date-time
          description: Date and time when the plan was created
        updated_at:
          type: string
          format: date-time
          description: Date and time when the plan was last updated
      required:
        - id
        - name
        - list_price
        - effective_price
        - billing_cycle
        - created_at
        - updated_at