import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars : SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    'Introduction',
    'Request idempotency',
    'Pagination',
    'Cached usage responses',
    'Dry run requests',
    'Error response format',
    'Reliability and scaling',
    'Rate limits',
    'Webhooks',
    {
      type: 'category',
      label: 'Endpoints',
      items: [
        {
          type: 'category',
          label: 'Accounts',
          link: {
            type: 'doc',
            id: 'Endpoints/accounts/Accounts'
          },
          items: [
            {
              type: 'doc',
              id: 'Endpoints/accounts/create-account',
              className: 'sidebar-item-post'
            },
            {
              type: 'doc',
              id: 'Endpoints/accounts/list-accounts',
              className: 'sidebar-item-get'
            }, 
            {
              type: 'doc',
              id: 'Endpoints/accounts/fetch-account',
              className: 'sidebar-item-get'
            }
          ],
        },
        {
          type: 'category',
          label: 'Users',
          link: {
            type: 'doc',
            id: 'Endpoints/users/Users'
          },
          items: [
            {
              type: 'doc',
              id: 'Endpoints/users/create-user',
              className: 'sidebar-item-post'
            },
            {
              type: 'doc',
              id: 'Endpoints/users/list-users', 
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id:'Endpoints/users/fetch-user',
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id:  'Endpoints/users/update-user',
              className: 'sidebar-item-put'
            },{
              type: 'doc',
              id:   'Endpoints/users/delete-user',
              className: 'sidebar-item-delete'
            },         
          ],
        },
        {
          type: 'category',
          label: 'Customers',
          link: {
            type: 'doc',
            id: 'Endpoints/customers/Customers'
          },
          items: [
            {
              type: 'doc',
              id:  'Endpoints/customers/create-customer',
              className: 'sidebar-item-post'
            },
            {
              type: 'doc',
              id:  'Endpoints/customers/list-customers',
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id:  'Endpoints/customers/fetch-customer',
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id:  'Endpoints/customers/update-customer',
              className: 'sidebar-item-put'
            },
            {
              type: 'doc',
              id:  'Endpoints/customers/delete-customer',
              className: 'sidebar-item-delete'
            },
          ],
        },
        {
          type: 'category',
          label: 'Entities',
          link: {
            type: 'doc',
            id: 'Endpoints/entities/Entities'
          },
          items: [
            {
              type: 'doc',
              id:  'Endpoints/entities/create-entity',
              className: 'sidebar-item-post'
            },
            {
              type: 'doc',
              id:  'Endpoints/entities/list-entities',
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id:  'Endpoints/entities/fetch-entity',
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id:  'Endpoints/entities/update-entity',
              className: 'sidebar-item-put'
            },
            {
              type: 'doc',
              id:  'Endpoints/entities/delete-entity',
              className: 'sidebar-item-delete'
            },
          ],
        },
        {
          type: 'category',
          label: 'S_l_Nexuses',
          link: {
            type: 'doc',
            id: 'Endpoints/s_l_nexuses/S_l_Nexuses'
          },
          items: [
            {
              type: 'doc',
              id: 'Endpoints/s_l_nexuses/create-s-l-nexus', 
              className: 'sidebar-item-post'
            },
            {
              type: 'doc',
              id: 'Endpoints/s_l_nexuses/list-s-l-nexuses', 
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id: 'Endpoints/s_l_nexuses/fetch-s-l-nexus',  
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id: 'Endpoints/s_l_nexuses/update-s-l-nexus', 
              className: 'sidebar-item-put'
            },
            {
              type: 'doc',
              id: 'Endpoints/s_l_nexuses/delete-s-l-nexus',
              className: 'sidebar-item-delete'
            },            
         ],
        },
        {
          type: 'category',
          label: 'Products',
          link: {
            type: 'doc',
            id: 'Endpoints/products/Products'
          },
          items: [
            {
              type: 'doc',
              id: 'Endpoints/products/create-product', 
              className: 'sidebar-item-post'
            },
            {
              type: 'doc',
              id: 'Endpoints/products/list-products',
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id: 'Endpoints/products/fetch-product',   
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id: 'Endpoints/products/update-product', 
              className: 'sidebar-item-put'
            },
            {
              type: 'doc',
              id: 'Endpoints/products/delete-product',
              className: 'sidebar-item-delete'
            },              
          ],
        },
        {
          type: 'category',
          label: 'Subscriptions',
          link: {
            type: 'doc',
            id: 'Endpoints/subscriptions/Subscriptions'
          },
          items: [
            {
              type: 'doc',
              id: 'Endpoints/subscriptions/create-subscription',  
              className: 'sidebar-item-post'
            },
            {
              type: 'doc',
              id: 'Endpoints/subscriptions/list-subscriptions', 
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id: 'Endpoints/subscriptions/fetch-subscription',   
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id: 'Endpoints/subscriptions/update-subscription', 
              className: 'sidebar-item-put'
            },
            {
              type: 'doc',
              id:'Endpoints/subscriptions/delete-subscription',
              className: 'sidebar-item-delete'
            },          
          ],
        },
        {
          type: 'category',
          label: 'Locations',
          link: {
            type: 'doc',
            id: 'Endpoints/locations/Locations'
          },
          items: [
            {
              type: 'doc',
              id: 'Endpoints/locations/create-location', 
              className: 'sidebar-item-post'
            },
            {
              type: 'doc',
              id: 'Endpoints/locations/list-locations', 
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id: 'Endpoints/locations/fetch-location', 
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id: 'Endpoints/locations/update-location',  
              className: 'sidebar-item-put'
            },
            {
              type: 'doc',
              id:  'Endpoints/locations/delete-location',
              className: 'sidebar-item-delete'
            },      
          ],
        },
        {
          type: 'category',
          label: 'Exemption Certificates',
          link: {
            type: 'doc',
            id: 'Endpoints/exemption certificates/Exemption-Certificate'
          },
          items: [
            {
              type: 'doc',
              id: 'Endpoints/exemption certificates/create-exemption-certificate', 
              label: 'Create',
              className: 'sidebar-item-post'
            },
            {
              type: 'doc',
              id: 'Endpoints/exemption certificates/list-exemption-certificates', 
              label: "List Exemption Certificates",
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id: 'Endpoints/exemption certificates/fetch-exemption-certificate',  
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id: 'Endpoints/exemption certificates/update-exemption-certificate', 
              className: 'sidebar-item-put'
            },
            {
              type: 'doc',
              id: 'Endpoints/exemption certificates/delete-exemption-certificate',
              className: 'sidebar-item-delete'
            },  
          ],              
        },
        {
          type: 'category',
          label: 'Location Attributes',
          link: {
            type: 'doc',
            id: 'Endpoints/location attributes/Location-Attributes'
          },
          items: [
            {
              type: 'doc',
              id: 'Endpoints/location attributes/create-location-attribute', 
              label: 'Create Location\nAttribute',
              className: 'sidebar-item-post'
            },
            {
              type: 'doc',
              id: 'Endpoints/location attributes/list-location-attributes', 
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id: 'Endpoints/location attributes/fetch-location-attribute', 
              className: 'sidebar-item-get'
            },
            {
              type: 'doc',
              id: 'Endpoints/location attributes/update-location-attribute', 
              className: 'sidebar-item-put'
            },
            {
              type: 'doc',
              id: 'Endpoints/location attributes/delete-location-attribute',
              className: 'sidebar-item-delete'
            },      
          ],
        },
      ],
    },
    
  ],
   
};

export default sidebars;
